name: JIRA Issue Status Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Extract Jira Issue ID from PR descritpion
      id: extract_issue_id
      run: |
        JIRA_REGEX='#[A-Z]+-[0-9]+'
        # Get the pull request description
        PR_DESCRIPTION="${{ github.event.pull_request.body }}"

        # Extract all matching JIRA IDs
        ISSUE_IDS=$(echo "$PR_DESCRIPTION" | grep -oE "$JIRA_REGEX" | tr -d '#')

        if [ -z "$ISSUE_IDS" ]; then
          echo "ERROR: No valid JIRA issue identifiers found in PR description."
          exit 1
        fi

        # Extract repo name
        REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)

        echo "JIRA issue IDs: $ISSUE_IDS"
        echo "Repo Name: $REPO_NAME"
        echo "issue_ids=$ISSUE_IDS" >> $GITHUB_ENV
        echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Check Jira Id's
      id: get_issue_status
      env:
        EMAIL: ${{ secrets.EMAIL }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        ISSUE_IDS: ${{ env.issue_ids }}
        REPO_NAME: ${{ env.repo_name }}
      run: |
        node checkJiraId2.js
